### PR TITLE
Added new tab with effort and catch data

### PR DESCRIPTION
**Pull request by gclawson1**
Hi Denisse, 

I finished adding a tab for the fishing effort and catch data. Right now it just pulls the data directly in from gem, but when we add the data to thredds we can pull it from there if we want. Take a look and let me know what you think. I'm not super attached to anything there so if you have suggestions/wanna make changes go right ahead!

### CODE REVIEW

**Comment by lidefi87** [comment]
Hi Gage,

The app uses the native R pipe: `|>` instead of the magrittr pipe: `%>%`. This will need to be updated before I can merge it.

I can see some lines of code are commented out and I cannot tell if these are meant to be kept or not. Please remove any lines of code that are not needed. 

It would be great if you follow the same formatting as the rest of the code, that is:
- Keep lines to a maximum of 80 characters to reduce horizontal scrolling (you can activate the "Show margin" option under Options > Code > Display
- Use curly brackets `{}` in `if` statements
- Avoid hard coding if possible. For example, in line 1132, you use `new_choices[1]`. Are you able to avoid this at all?
- Comments should be written on the line before the line of code being described, not next to it.
- Data should be loaded under the `Defining location of relevant data sources` section.

The idea behind this is that the code is easy to read, which we hope in turn will incentivise people to contribute towards the development of the app.

Also, it appears you are using an outdated version of the code (version 1.0.2) that does not include the "download" button in the comparison tab (version 1.1.0). Could you please use the most up to date version of the app?

**Comment by lidefi87** [comment]
In regards to the comments about making the app faster. You can do this by avoiding processing your data every time you load it. For example, you remove any rows in the effort data that have no information under the `region` column and then you rename the `FGroup` column. 

Instead of doing this every time the app is started, it would be better to simply save the data as you need it to minimise or avoid any processing in the app itself. 

You may also want to consider creating a file for each region as it was done for the GFDL and WOA data.

**Comment by gclawson1** [comment]
Hey Denisse, 

Just updating you; I'm working on making those changes and will push the updated branch (using the most recent version of the app) later today!

**Comment by gclawson1** [comment]
Hi @lidefi87, 

I've just pushed all of the changes I needed to make. Everything runs smoothly and quickly now. Please let me know if there's anything I missed. 

Best,
Gage

**Comment by lidefi87** [comment]
Thanks, Gage. I may be a bit delayed in checking this PR, but I'll get back to you by the end of the week. Thanks for your help 😊

**Comment by lidefi87** [comment]
All merged now. Thanks again for your help

**Comment by gclawson1** [comment]
Thanks @lidefi87 !!

**Pull request merged**
